AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
  WebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref WebVPC
  WebBackupSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: "true"
      VpcId: !Ref WebVPC
  DBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref WebVPC
  DBBackupSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.4.0/24
      VpcId: !Ref WebVPC
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet Group for DB
      SubnetIds:
        - !Ref DBSubnet
        - !Ref DBBackupSubnet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref WebVPC
      InternetGatewayId: !Ref InternetGateway
  WebRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref WebVPC
  WebInternetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref WebRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  WebSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WebSubnet
      RouteTableId: !Ref WebRouteTable
  WebBackupSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref WebBackupSubnet
      RouteTableId: !Ref WebRouteTable
Outputs:
  VPC:
    Value: !Ref WebVPC
    Export: 
      Name: VPCID
  WebSubnet:
    Value: !Ref WebSubnet
    Export:
      Name: WebSubnetID
  WebBackupSubnet:
    Value: !Ref WebBackupSubnet
    Export:
      Name: WebBackupSubnetID
  DBSubnetGroup:
    Value: !Ref DBSubnetGroup
    Export:
      Name: DBSubnetGroupID
