AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Web-SG
      GroupDescription: Security Group for Web Server
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  WebKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: web-keypair
Outputs:
  SecGroup:
    Value: !Ref WebSecGroup
    Export: 
      Name: SecurityGroupID
  KeyPair:
    Value: !Ref WebKeyPair
    Export: 
      Name: KeyPairName
