AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SSHFromAddress:
    Type: String
Resources:
  EC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Web-SG
      GroupDescription: Security Group for Web Server
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHFromAddress
  WebKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: web-keypair
  DBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: DB-SG
      GroupDescription: Security Group for DB Server
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.1.0/24
  ALBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ALB-SG
      GroupDescription: Security Group for ALB
      VpcId: !ImportValue VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Outputs:
  EC2SSMRole:
    Value: !Ref EC2SSMRole
    Export: 
      Name: EC2SSMRoleID
  SecGroup:
    Value: !Ref WebSecGroup
    Export: 
      Name: SecurityGroupID
  KeyPair:
    Value: !Ref WebKeyPair
    Export: 
      Name: KeyPairName
  DBSecGroup:
    Value: !Ref DBSecGroup
    Export: 
      Name: DBSecurityGroupID
  ALBSecGroup:
    Value: !Ref ALBSecGroup
    Export: 
      Name: ALBSecurityGroupID
